-- CreateTable
CREATE TABLE "projects" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "projectName" TEXT NOT NULL,
    "customerName" TEXT NOT NULL,
    "facilityLocation" TEXT,
    "versionNumber" TEXT NOT NULL DEFAULT 'v1.0',
    "bastianRep" TEXT,
    "step1Complete" BOOLEAN NOT NULL DEFAULT false,
    "step2Complete" BOOLEAN NOT NULL DEFAULT false,
    "step3Complete" BOOLEAN NOT NULL DEFAULT false,
    "step4Complete" BOOLEAN NOT NULL DEFAULT false,
    "step5Complete" BOOLEAN NOT NULL DEFAULT false,
    "maxLoadWeightLbs" REAL NOT NULL DEFAULT 0,
    "typicalUnitType" TEXT NOT NULL DEFAULT '',
    "palletBottomBoard" TEXT,
    "customPalletDescription" TEXT,
    "otherUnitTypeDescription" TEXT,
    "loadLengthIn" REAL,
    "loadWidthIn" REAL,
    "loadHeightIn" REAL,
    "transferMethod" TEXT NOT NULL DEFAULT '',
    "deliveryPattern" TEXT NOT NULL DEFAULT '',
    "maxLiftHeightFt" REAL,
    "minAisleWidthFt" REAL NOT NULL DEFAULT 0,
    "floorCondition" TEXT NOT NULL DEFAULT '',
    "shiftsPerDay" INTEGER NOT NULL DEFAULT 1,
    "hoursPerShift" REAL NOT NULL DEFAULT 8,
    "operatingDaysPattern" TEXT NOT NULL DEFAULT '',
    "operatingDaysCustom" JSONB,
    "breaksPerShift" INTEGER NOT NULL DEFAULT 0,
    "breakDurationMin" INTEGER NOT NULL DEFAULT 0,
    "requiredThroughputPerHour" INTEGER NOT NULL DEFAULT 0,
    "avgDistanceFt" REAL NOT NULL DEFAULT 0,
    "distanceType" TEXT NOT NULL DEFAULT 'one_way',
    "operatorsPerShift" INTEGER NOT NULL DEFAULT 0,
    "rampDistanceFt" REAL NOT NULL DEFAULT 0,
    "maxRampGrade" REAL NOT NULL DEFAULT 0,
    "oemDealer" TEXT,
    "dealershipName" TEXT,
    "dealerRep" TEXT,
    "certifications" JSONB NOT NULL DEFAULT [],
    "interlocks" JSONB NOT NULL DEFAULT [],
    "otherAGVs" BOOLEAN NOT NULL DEFAULT false,
    "otherAGVVendor" TEXT,
    "tempMinF" REAL,
    "tempMaxF" REAL,
    "outdoorRequired" BOOLEAN NOT NULL DEFAULT false,
    "freezerCapable" BOOLEAN NOT NULL DEFAULT false,
    "dustMoisture" TEXT,
    "wmsRequired" BOOLEAN NOT NULL DEFAULT false,
    "wmsVendor" TEXT,
    "projectNotes" TEXT
);

-- CreateIndex
CREATE INDEX "projects_createdAt_idx" ON "projects"("createdAt");

-- CreateIndex
CREATE INDEX "projects_updatedAt_idx" ON "projects"("updatedAt");
